# Generated by Django 4.2.19 on 2025-03-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100)),
                ('correu', models.CharField(max_length=100)),
                ('curs', models.CharField(max_length=10)),
                ('modulsMatriculats', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100)),
                ('correu', models.CharField(max_length=100)),
                ('curs', models.CharField(max_length=10)),
                ('tutor', models.CharField(max_length=100)),
                ('moduls', models.IntegerField()),
            ],
        ),
    ]
