# Generated by Django 4.2.19 on 2025-03-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='correu',
            field=models.EmailField(max_length=100),
        ),
    ]
